### ISSUE TITLE
Use regex to prevent spambots w/ similar names

### ISSUE THREAD

**Issue by kenpaicat** [SloveniaEngineering/laguna-backend#102]
## Description

<Title>

Proposed by @Skrivni.

This is low priority questionable because what would be classified as "similar".

Example given:

> u smislu maš račun shoddy, filter blokira npr. shodddy

## Implementation steps

* [ ] Example of custom validator: https://github.com/SloveniaEngineering/laguna-backend/blob/master/crates/laguna-backend-dto/src/validators/login.rs#L7
* [ ] Uporaba te funkcije: https://github.com/SloveniaEngineering/laguna-backend/blob/3daa73afe080d88692044942e4cde12edba52521/crates/laguna-backend-dto/src/login.rs#L10
* [ ] eveda ta "regex similarity validator" bi šel sem (zraven): https://github.com/SloveniaEngineering/laguna-backend/blob/3daa73afe080d88692044942e4cde12edba52521/crates/laguna-backend-dto/src/register.rs#L17-L20
* [ ] In pa še test (register z podobnim username-om) semle: https://github.com/SloveniaEngineering/laguna-backend/blob/master/crates/laguna-backend-api/tests/auth.rs

## Technical considerations

* Would require `SIMILAR TO` or `POSIX` or `LIKE` db poll https://www.postgresql.org/docs/current/functions-matching.html
* This causes performance penalty

**Comment by kenpaicat** [comment]
Triaged today by @kozabrada123 @kenpaicat
