### ISSUE TITLE
[BE] Basic DB Models

### ISSUE THREAD

**Issue by kenpaicat** [SloveniaEngineering/laguna-backend#2]
Check this out: https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/database/schema.pdf

### User
* [x] id (uuid, v4)
* [x] username (string, unicode, escaped)
* [x] email (string, unicode, specific format)
* [x] password (hash)
* [x] first_login (datetime for account age)
* [x] last_login (datetime)
* [x] avatar_url (usually "link to avatar provider" + hash(email))
* [x] role (enum) 
  * [x] user
  * [x] verified
  * [x] mod
  * [x] admin
* [x] behaviour (enum, computable from Torrent)
  * [x] lurker (default, potential leech)
  * [x] downloader (could be leech, but not known yet due to file not transferred fully)
  * [x] freeleecher (never uploads, but thats fine because he is doing it on Freeleech)
  * [x] leech (never uploads, ratio upload:download is very low — bad user)
  * [x] seed (downloads and seeds for other users — good user)
  * [x] chocked (seed but; uploading at full capacity || using blacklisted torrent client || all downloaders of this seed are seed ergo. completely uninterested)
  * [x] uploader (seed which added Torrent to this DB — best user)
* [x] is_active (bool) (#9 )
* [x] has_verified_email (bool)
* [x] is_history_private (bool, history not visible) (#11 )
* [x] is_profile_private (bool, profile not visible)
* [WILL_BE_COMPUTED] bytes_downloaded (bigint or decimal, computable from Torrent) (should probably be VIEW-ed)
* [WILL_BE_COMPUTED] bytes_uploaded (bigint or decimal, computable from Torrent) (should probably be VIEW-ed)

#### DTOs
* [x] UserDTO
* [x] LoginDTO
* [x] RegisterDTO

#### User API
* [x] JWT Authorization and Role claim (#1 )
* [x] POST (#4 )
  * [x] `/register`
    * [x] Documentation
  * [x] `/login`
    * [x] Documentation
* [ ] PATCH (#5 ) 
* [x] DELETE (#6 ) 
* [x] GET (#7 ) 
* [NOT PLANNED] PUT (#8 )

### Torrent
* [x] id (uuid)
* [x] name (string)
* [x] file_name (string)
* [x] nfo (null or string)
* [x] path (pathbuf)
* [x] info_hash (hash of info section of torrent file at path "path")
* [x] uploaded_by (FK onto User)
* [x] modded_ by (FK onto User)

#### Torrent API (Tracker)
* [x] #30
* [x] #31
* [ ] #33
* [x] #32
