### ISSUE TITLE
[BE] Torrent file storage

### ISSUE THREAD

**Issue by kenpaicat** [SloveniaEngineering/laguna-backend#77]
## Description

Torrent file should be stored in DB due to relatively small size for now.
Some parts of the torrent file (info section fields) ~~can be~~ are decoded on upload and stored directly into table to avoid encoding-decoding everytime it is requested.

## Resources 
* https://github.com/webtorrent/bittorrent-tracker
* https://en.wikipedia.org/wiki/Torrent_file
* https://github.com/Luminarys/synapse
* https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/master
* Rust implementacija: https://github.com/torrust
* Rust implementacija trackerja: https://github.com/greatest-ape/aquatic/tree/master
* Use Web Actor Framework: https://crates.io/crates/actix-web-actors
* Specs: https://wiki.theory.org/Main_Page
* BT infra: https://github.com/GGist/bip-rs/tree/master

## API

API for Bittorrent v1 only. We might support v2 later.

* [x] `PUT /api/torrent`
  * [x] Verify `info_hash`
  * [x] Formatting needs to be "verified" by `serde` via type system.
  * [ ] Additional integrity checks (described at http://bittorrent.org).
  * [x] Support for `application/x-bittorrent` instead of `form/multipart-data`.
* [x] `PATCH /api/torrent/{info_hash}` using `TorrentPatchDTO`.
* [x] `DELETE /api/torrent/{info_hash}`

## Notes / ideas

* Storage: The `numwant` param of Peer(s)'s request determines how wanted this file is. If highly wanted (30+) we might promote this file into an in-memory storage using `actix-redis` KV store.
* Automatic purge of file from RAM/DISK if low download count after X seconds.
* Can we patch bencoded torrent fields?
* How to avoid serialization and deserialization as much as possible? (looking at JSON postgres and serde + sqlx)
